In [2]:
! pip install numpy

## Basic Numpy

**NumPy (Numerical Python)** is a fundamental package for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. NumPy is widely used in scientific, engineering, and data science applications where numerical data processing is paramount.

### Key Features of NumPy:

1. **N-dimensional Array Object (`ndarray`)**:
   - NumPy's core feature is its `ndarray`, a multi-dimensional array object.
   - Arrays in NumPy are homogeneous and can contain elements of a single data type (`dtype`), typically numerical (integers, floats), but also booleans, strings, etc.
   
   - Arrays can be created from Python lists or tuples using `np.array()`.

2. **Efficient Operations**:
   - NumPy provides vectorized operations, which allow for element-wise operations and broadcasting.
   - These operations are implemented in C and are much faster than their pure Python counterparts that use loops.

3. **Broadcasting**:
   - Broadcasting allows NumPy to perform operations on arrays of different shapes.
   - It extends smaller arrays to match the shape of larger arrays during arithmetic operations, which makes code cleaner and faster.

4. **Mathematical Functions**:
   - NumPy offers a wide range of mathematical functions that operate element-wise on arrays.
   - Functions include trigonometric functions, exponential and logarithmic functions, statistical functions, etc.

5. **Array Manipulation**:
   - NumPy provides functions for reshaping, slicing, merging, and splitting arrays.
   - These operations allow for efficient data manipulation and extraction.

6. **Linear Algebra**:
   - NumPy has a rich library for linear algebra operations, such as matrix multiplication (`np.dot()`), matrix decomposition (`np.linalg.inv()`, `np.linalg.eig()`), solving linear equations, and more.

7. **Random Number Generation**:
   - NumPy provides functions to generate random numbers and random samples from different probability distributions.

8. **Integration with Other Libraries**:
   - NumPy integrates well with other libraries in the scientific computing ecosystem, such as SciPy (scientific computing), Matplotlib (plotting), Pandas (data manipulation), and more.

### Example Usage of NumPy:

Here are a few examples demonstrating the usage of NumPy:

#### Creating an Array:

```python
import numpy as np

# Creating a 1-dimensional array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Creating a 2-dimensional array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
```

#### Performing Operations:

```python
# Element-wise arithmetic operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # Output: [5 7 9]
print(a * b)  # Output: [4 10 18]

# Broadcasting
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([10, 20, 30])

print(c + d)  # Output: [[11 22 33] [14 25 36]]
```

#### Linear Algebra Operations:

```python
# Matrix multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result = np.dot(matrix1, matrix2)
print(result)  # Output: [[19 22] [43 50]]

# Finding eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix1)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)
```

### Benefits of Using NumPy:

- **Efficiency**: NumPy operations are implemented in C, making them faster than pure Python equivalents.
- **Ease of Use**: Provides a simple and intuitive interface for numerical operations.
- **Broad Applicability**: Used in various domains including scientific computing, machine learning, signal processing, etc.
- **Integration**: Works seamlessly with other libraries in the Python ecosystem.

NumPy's power lies in its ability to handle large datasets efficiently and perform complex mathematical computations with ease, making it an essential tool for anyone working with numerical data in Python.

In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3,4], dtype='int32')
print(a)

[1 2 3 4]


In [5]:
b = np.array([[1.0,2.0,3.0,4.0],[5.0,6.0,7.0,8.0]])
print(b)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [6]:
# Get Dimension
print(a.ndim)

1


In [7]:
# Get the shape

print(a.shape)
print(b.shape)

(4,)
(2, 4)


In [8]:
# Get type
print(b.dtype)
print(a.dtype)

float64
int32


In [9]:
# Get Size

print(a.size)
print(a.itemsize)

4
4


In [10]:
# Get Total Size
print(a.size * a.itemsize)

print(a.nbytes)

16
16


## Accessing/Changing specific elements, rows, columns, etc

In [11]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
# Get shape
print(a.shape)

(2, 7)


In [13]:
# Get specif element in the array (r,c)
print(a[1,5])

13


In [14]:
# Get specific element in row
print(a[0,:])
print(a[0,4])
print(a[0:])

[1 2 3 4 5 6 7]
5
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
# Get the specific column

print(a[:,2])

[ 3 10]


In [16]:
# Getting little more fancy elements [startindex:endindex:stepindex]

print(a[0,1:6:2])
print(a[1,1:14:2])

print(a[0,1:-2:2])

[2 4 6]
[ 9 11 13]
[2 4]


In [17]:
#Update the data in particular position

a[1,5] = 20
print(a)

a[:,2] = 5
print(a)

a[:,2] =[1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### *3-d example

In [18]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [19]:
# Get specific element

print(b[0,1,1])

print(b[1,1,1])
``
print(b[:,1,:])

print(b[:,1,1])

4
8
[[3 4]
 [7 8]]
[4 8]


In [20]:
# Replace 

b[:,1,:] =[[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### Initializing Different Types of Arrays

In [21]:
# All 0's matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [22]:
# All 1's matrix 
np.ones((2,4),dtype='int32')

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [23]:
# Any other numbers

np.full((2,3),55)

np.full((3,2),99, dtype='float32')

array([[99., 99.],
       [99., 99.],
       [99., 99.]], dtype=float32)

In [24]:
# Any other numbers (full-like)
np.full_like(a,8)

array([[8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8]])

In [25]:
# Random decimal numbers

np.random.rand(2,4)

array([[0.21454426, 0.94602165, 0.24197739, 0.82334885],
       [0.05949713, 0.05183043, 0.40097454, 0.56707889]])

In [26]:
np.random.random_sample(a.shape)

array([[0.92550847, 0.65097345, 0.72399393, 0.5097491 , 0.10678274,
        0.23626221, 0.00834052],
       [0.67693983, 0.62404573, 0.1536072 , 0.99646085, 0.87490357,
        0.30322356, 0.23797564]])

In [27]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-4,  4, -3],
       [ 4,  1,  6],
       [ 6, -4,  0]])

In [28]:
np.random.randint(7, size=(3,3))

array([[0, 4, 0],
       [1, 0, 5],
       [5, 4, 6]])

In [29]:
# The identity Matrix

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
# Repeat an array (axis=0, axis=1)

arr = np.array([[1,2,3]])
rs1 = np.repeat(arr,3,axis=0)
print(rs1)

arr = np.array([[1,2,3]])
rs1 = np.repeat(arr,3,axis=1)
print(rs1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [37]:
output = np.ones((5,5))
print(output)

zero = np.zeros((3,3))
zero[1,1] =9
print(zero)

output[1:-1,1:-1] =zero 
print(output)

# Be careful when copying arrays!!!

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [47]:
out = np.array([1,2,3])

# without copy function, all the values are same 
out1 = out.copy()
out1[0] = 100
print(out1)



[1 2 3]


In [49]:
# with copy function, it should be different
out1 = out.copy()
out1[0] = 100
print(out1)

[100   2   3]


#### Mathematics

In [50]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [52]:
a+2

array([3, 4, 5, 6])

In [53]:
a-2

array([-1,  0,  1,  2])

In [54]:
a*2

array([2, 4, 6, 8])

In [55]:
a//2

array([0, 1, 1, 2])

In [56]:
b=np.array([1,0,1,0])
print(b)

[1 0 1 0]


In [57]:
a+b

array([2, 2, 4, 4])

In [60]:
a**2

array([ 1,  4,  9, 16])

In [61]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [62]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [66]:
a= np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

c=np.matmul(a,b)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [68]:
# Find the determinant
c=np.identity(3)
np.linalg.det(c)


1.0

In [69]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

#### Statistics

In [70]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
np.min(stats)

1

In [72]:
np.max(stats, axis=1)

array([3, 6])

In [73]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [74]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [75]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [76]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [77]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [78]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])